IF
	Die()
	!InMyArea("C6KACH")
	Global("Die","LOCALS",0)
	Global("ShadowFightBodhi","GLOBAL",1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("Die","LOCALS",1)
		CreateCreature("C6KACH",[1374.654],0) // Kachiko
		Wait(1)
		DisplayStringHead("c6arkan",54855) // Hah! Taste my steel, fiend. Ho, <CHARNAME>! Let us finish this!
		ReallyForceSpellDead(Myself,VAMPIRE_GAS_FORM_CHANGE)
		SetInterrupt(TRUE)
END